import type { HelpState } from '../hooks/useHelp.ts';
import { MarkdownAnswer } from './MarkdownAnswer.tsx';

interface Props {
  id: string;
  labelledBy: string;
  state: HelpState;
  onRetry: () => void;
}

/**
 * The announcement contract, which is why this is its own component:
 *
 * - The `role="status"` line holds only a short sentence, and it is present for
 *   every state, so the transition that matters (pending to "Explanation ready.")
 *   happens with the region already in the DOM.
 * - The answer itself is deliberately outside any live region. Marking a 400-word
 *   block live makes a screen reader read the whole thing aloud, and read it
 *   again on every re-render.
 * - Errors get `role="alert"`, because a failure is worth interrupting for.
 * - Focus never moves when the answer arrives. The button is a disclosure with
 *   `aria-expanded`, so the panel is already the next thing in reading and tab
 *   order. Stealing focus into async content is what causes "where am I?".
 * - The retry control lives outside the state branches. Inside them, pressing it
 *   would unmount the very button holding focus, dropping the keyboard user to
 *   the top of the document, which is the exact defect the rule above avoids.
 */
export function HelpPanel({ id, labelledBy, state, onRetry }: Props) {
  return (
    <div id={id} className="help" role="group" aria-labelledby={labelledBy}>
      <div className="help__row">
        {state.status === 'pending' ? <span className="spinner" aria-hidden="true" /> : null}
        <p className="help__status" role="status">
          {state.status === 'pending' ? 'Asking the AI assistant\u2026' : null}
          {state.status === 'ok' ? 'Explanation ready.' : null}
        </p>
      </div>

      {state.status === 'error' ? (
        <p className="help__error" role="alert">
          {state.message}
        </p>
      ) : null}

      {state.status === 'ok' ? (
        <>
          <h5 className="help__h">AI explanation</h5>
          <MarkdownAnswer markdown={state.markdown} />
          <p className="help__disclaimer">
            Generated by {state.model}. Automated advice, not a compliance sign-off: check it
            against the linked WCAG guidance before shipping a fix.
          </p>
        </>
      ) : null}

      {/* Rendered for every state, pending included. Excluding pending would
          unmount the row on click, replacing the focused button with a new DOM
          node and dropping the keyboard user to the top of the document, which is
          the exact defect this arrangement exists to avoid. Same element type,
          class and position every time, so React keeps the node and focus with
          it, and the label change is announced because the accessible name
          changes while the button holds focus. */}
      <p className="help__actions">
        <button
          type="button"
          className="btn btn--ghost"
          aria-disabled={state.status === 'pending' || undefined}
          onClick={() => {
            if (state.status !== 'pending') onRetry();
          }}
        >
          {state.status === 'error' ? 'Try again' : 'Regenerate'}
        </button>
      </p>
    </div>
  );
}
